import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent  {
  constructor(private router: Router) { }
  
  dashboardDetailsList= [
    {
        "AppStageId": 8,
        "source": "SELF",
        "thirdMedicalRequirement": " ",
        "primaryLastName": "Bramhe",
        "loanRefNumber": "123444455555",
        "ConsentStatus": "Consent Pending",
        "disbursementDate": "",
        "fourthMedicalRequirement": " ",
        "SQ": "0",
        "memberConsentRequired": "Y",
        "MobileNo": "9821789100",
        "memberFormStatus": "Half Filled",
        "secMedicalRequirement": " ",
        "PKLRFId": 285932,
        "SumAssured": 100000,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "premiumDebitDate": "",
        "completedDate": "-",
        "transactionId": "",
        "branchCode": "10656",
        "TotalCount": 597,
        "loanAccountNumber": "123444455555",
        "debitAccountNo": "",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1717666997070,
        "medicalRequirement": "  ",
        "primaryFirstName": "Eshwari",
        "primaryMiddleName": "",
        "RiderSumAssured": null
    },
    {
        "AppStageId": 5,
        "source": "SELF",
        "thirdMedicalRequirement": " ",
        "primaryLastName": "gjhgj",
        "loanRefNumber": "799876876",
        "ConsentStatus": "Pending Form",
        "disbursementDate": "",
        "fourthMedicalRequirement": " ",
        "SQ": "1",
        "memberConsentRequired": "Y",
        "MobileNo": "9876543210",
        "memberFormStatus": "Half Filled",
        "secMedicalRequirement": " ",
        "PKLRFId": 285931,
        "SumAssured": 79999,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "premiumDebitDate": "",
        "completedDate": "-",
        "transactionId": "",
        "branchCode": "10422",
        "TotalCount": 597,
        "loanAccountNumber": "7687698798790",
        "debitAccountNo": "",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1717664497780,
        "medicalRequirement": "  ",
        "primaryFirstName": "hghgj",
        "primaryMiddleName": "hgjhgjh",
        "RiderSumAssured": null
    },
    {
        "AppStageId": 5,
        "source": "SELF",
        "thirdMedicalRequirement": " ",
        "primaryLastName": "hgjhgj",
        "loanRefNumber": "7868687689",
        "ConsentStatus": "Pending Form",
        "disbursementDate": "",
        "fourthMedicalRequirement": " ",
        "SQ": "2",
        "memberConsentRequired": "Y",
        "MobileNo": "8798798798",
        "memberFormStatus": "Half Filled",
        "secMedicalRequirement": " ",
        "PKLRFId": 285930,
        "SumAssured": 80000,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "premiumDebitDate": "",
        "completedDate": "-",
        "transactionId": "",
        "branchCode": "10416",
        "TotalCount": 597,
        "loanAccountNumber": "987654653536",
        "debitAccountNo": "",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1717664194877,
        "medicalRequirement": "  ",
        "primaryFirstName": "jhgjhg",
        "primaryMiddleName": "jhgjhgj",
        "RiderSumAssured": null
    },
    {
        "AppStageId": 9,
        "source": "SELF",
        "thirdMedicalRequirement": " ",
        "primaryLastName": "Sundar",
        "loanRefNumber": "1307918000112",
        "ConsentStatus": "Manual Consent",
        "disbursementDate": "01/01/2024",
        "fourthMedicalRequirement": " ",
        "SQ": "3",
        "memberConsentRequired": "N",
        "MobileNo": "9930917914",
        "memberFormStatus": "Full Filled",
        "secMedicalRequirement": " ",
        "PKLRFId": 285928,
        "SumAssured": 10000000,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "premiumDebitDate": "27/05/2024",
        "completedDate": "-",
        "transactionId": "wewye8734873847384",
        "branchCode": "10397",
        "TotalCount": 597,
        "loanAccountNumber": "1307918000112",
        "debitAccountNo": "1307918000112",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1717416961420,
        "medicalRequirement": "  ",
        "primaryFirstName": "Mahesh",
        "primaryMiddleName": "",
        "RiderSumAssured": null
    },
    {
        "AppStageId": 2,
        "source": "SELF",
        "thirdMedicalRequirement": " ",
        "primaryLastName": "Sundar",
        "loanRefNumber": "1307198109898",
        "ConsentStatus": "Pending Form",
        "disbursementDate": "",
        "fourthMedicalRequirement": " ",
        "SQ": "4",
        "memberConsentRequired": "Y",
        "MobileNo": "9930917914",
        "memberFormStatus": "Half Filled",
        "secMedicalRequirement": null,
        "PKLRFId": 285927,
        "SumAssured": 1000000,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "premiumDebitDate": "",
        "completedDate": "-",
        "transactionId": "",
        "branchCode": "10416",
        "TotalCount": 597,
        "loanAccountNumber": "1307198109898",
        "debitAccountNo": "",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1717404290207,
        "medicalRequirement": "  ",
        "primaryFirstName": "Mahesh",
        "primaryMiddleName": "",
        "RiderSumAssured": null
    },
    {
        "AppStageId": 6,
        "jointMidlleName": "",
        "source": "SELF",
        "thirdMedicalRequirement": "  ",
        "primaryLastName": "ABC",
        "loanRefNumber": "WAPT00000002",
        "ConsentStatus": "Pending Form",
        "disbursementDate": "",
        "jointFirstName": "PQR",
        "fourthMedicalRequirement": "  ",
        "SQ": "5",
        "memberConsentRequired": "Y",
        "MobileNo": "8888888888",
        "memberFormStatus": "Half Filled",
        "secMedicalRequirement": "  ",
        "PKLRFId": 285926,
        "SumAssured": 100000,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "jointLastName": "PQR",
        "premiumDebitDate": "",
        "completedDate": "-",
        "transactionId": "",
        "branchCode": "10656",
        "TotalCount": 597,
        "loanAccountNumber": "WAPT00000002",
        "debitAccountNo": "",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1716556499140,
        "medicalRequirement": "  ",
        "primaryFirstName": "ABC",
        "primaryMiddleName": "",
        "RiderSumAssured": null
    },
    {
        "AppStageId": 9,
        "jointMidlleName": "",
        "source": "SELF",
        "thirdMedicalRequirement": "  ",
        "primaryLastName": "Rane",
        "loanRefNumber": "13071981123001",
        "ConsentStatus": "Digital Consent",
        "disbursementDate": "",
        "jointFirstName": "Sharath",
        "fourthMedicalRequirement": "  ",
        "SQ": "6",
        "memberConsentRequired": "N",
        "MobileNo": "9930917914",
        "memberFormStatus": "Full Filled",
        "secMedicalRequirement": "  ",
        "PKLRFId": 285925,
        "SumAssured": 7500000,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "jointLastName": "Shriyan",
        "premiumDebitDate": "",
        "completedDate": "-",
        "transactionId": "",
        "branchCode": "10391",
        "TotalCount": 597,
        "loanAccountNumber": "13071981123001",
        "debitAccountNo": "",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1716554630630,
        "medicalRequirement": "  ",
        "primaryFirstName": "Parag",
        "primaryMiddleName": "",
        "RiderSumAssured": null
    },
    {
        "AppStageId": 2,
        "source": "SELF",
        "thirdMedicalRequirement": " ",
        "primaryLastName": "ABC",
        "loanRefNumber": "WAPT00000001",
        "ConsentStatus": "Pending Form",
        "disbursementDate": "",
        "fourthMedicalRequirement": " ",
        "SQ": "7",
        "memberConsentRequired": "Y",
        "MobileNo": "8888888888",
        "memberFormStatus": "Half Filled",
        "secMedicalRequirement": " ",
        "PKLRFId": 285924,
        "SumAssured": 50000,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "premiumDebitDate": "",
        "completedDate": "-",
        "transactionId": "",
        "branchCode": "10397",
        "TotalCount": 597,
        "loanAccountNumber": "WAPT00000001",
        "debitAccountNo": "",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1716546352143,
        "medicalRequirement": "  ",
        "primaryFirstName": "ABC",
        "primaryMiddleName": "",
        "RiderSumAssured": null
    },
    {
        "AppStageId": 6,
        "source": "SELF",
        "thirdMedicalRequirement": " ",
        "primaryLastName": "fdsfdsf",
        "loanRefNumber": "87987",
        "ConsentStatus": "Pending Form",
        "disbursementDate": "",
        "fourthMedicalRequirement": " ",
        "SQ": "8",
        "memberConsentRequired": "Y",
        "MobileNo": "9923748354",
        "memberFormStatus": "Half Filled",
        "secMedicalRequirement": " ",
        "PKLRFId": 285923,
        "SumAssured": 400000,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "premiumDebitDate": "",
        "completedDate": "-",
        "transactionId": "",
        "branchCode": "10408",
        "TotalCount": 597,
        "loanAccountNumber": "87987987798798",
        "debitAccountNo": "",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1716449430617,
        "medicalRequirement": "  ",
        "primaryFirstName": "fdsfsf",
        "primaryMiddleName": "sfsfsdfds",
        "RiderSumAssured": null
    },
    {
        "AppStageId": 6,
        "source": "SELF",
        "thirdMedicalRequirement": " ",
        "primaryLastName": "test",
        "loanRefNumber": "UYTUUYUYTUY",
        "ConsentStatus": "Pending Form",
        "disbursementDate": "",
        "fourthMedicalRequirement": " ",
        "SQ": "9",
        "memberConsentRequired": "Y",
        "MobileNo": "9923748354",
        "memberFormStatus": "Half Filled",
        "secMedicalRequirement": " ",
        "PKLRFId": 285922,
        "SumAssured": 500000,
        "medicalReqStatus": "OPEN",
        "TotalPremiumAmountWithTaxes": null,
        "premiumDebitDate": "",
        "completedDate": "-",
        "transactionId": "",
        "branchCode": "10422",
        "TotalCount": 597,
        "loanAccountNumber": "876869989898",
        "debitAccountNo": "",
        "loanApplicationStatus": "Approved",
        "ApplicationStatus": null,
        "CreatedDate": 1716189899183,
        "medicalRequirement": "  ",
        "primaryFirstName": "test",
        "primaryMiddleName": "testt",
        "RiderSumAssured": null
    }
]
  navigateTo(route: string) {
    this.router.navigate([route]);
  }
  onFinalSubmit() {
    console.log('Final submission logic here');
  }

}
